name: Release source package

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    uses: kelvralang/package-actions/.github/workflows/source-release.yml@v1
    with:
      package_name: package-template
